---
title: "Forecasting"
author: "Yue Chen, Kai Kang, Jiaqian Ma, Yinzhe Huang"
date: "2022/1/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("C:/Users/69560/Desktop/forecasting_R/utils.R")
source("C:/Users/69560/Desktop/forecasting_R/dataUtils.R")
```

### Dataset splition
```{r}
rawData <-  read_csv("C:/Forecasting/Projectdata.csv")
trainData = rawData[c(1:(nrow(rawData)-28)),]
testData = rawData[c((nrow(rawData)-27):nrow(rawData)),]
```

### Aggregation
```{r}
# by categories
trainAggCat = agg_by_cat(trainData)
testAggCat = agg_by_cat(testData)
# by week
trainAggWeek = agg_by_week(trainData)
testAggWeek = agg_by_week(testData)
# by store
trainAggStore = agg_by_store(trainData)
testAggStore = agg_by_store(testData)
```

#1.2 benchmarks

##1) Naive 
```{r warning=False} 
library(fpp2)
ts_list = lapply(trainData[,2:ncol(rawData)], ts)
devisors = unlist(lapply(trainData[,2:ncol(trainData)], cal.devisor))
crossH_RMSSE_naive = data.frame()

for (h in 1:28) {
  pred_list_naive = lapply(ts_list, naive, h=h)
  RMSSE_v_naive = eval.RMSSE(testData, pred_list_naive, h = h, devisor = devisors)
  crossH_RMSSE_naive = rbind(crossH_RMSSE_naive, RMSSE_v_naive)
}
names(crossH_RMSSE_naive) = names(RMSSE_v_naive)
crossH_RMSSE_naive
```
## 2) sNaive 
```{r warning=False} 
ts_list = lapply(trainData[,2:ncol(rawData)], ts)
devisors = unlist(lapply(trainData[,2:ncol(trainData)], cal.devisor))
crossH_RMSSE_snaive = data.frame()

for (h in 1:28) {
  pred_list_snaive = lapply(ts_list, snaive, h=h)
  RMSSE_v_snaive = eval.RMSSE(testData, pred_list_snaive, h = h, devisor = devisors)
  crossH_RMSSE_snaive = rbind(crossH_RMSSE_snaive, RMSSE_v_snaive)
}
names(crossH_RMSSE_snaive) = names(RMSSE_v_snaive)
crossH_RMSSE_snaive
```
## 4) MA
```{r warning=False} 
library(smooth)
ts_list = lapply(trainData[,2:ncol(rawData)], ts)
devisors = unlist(lapply(trainData[,2:ncol(trainData)], cal.devisor))
crossH_RMSSE_ma = data.frame()

for (h in 1:28) {
  pred_list_ma = lapply(ts_list,sma,h=h)
  RMSSE_v_ma = eval.RMSSE(testData, pred_list_ma, h = h, devisor = devisors)
  crossH_RMSSE_ma = rbind(ses_crossH_RMSSE, RMSSE_v_ma)
}
names(crossH_RMSSE_ma) = names(RMSSE_v_ma)
crossH_RMSSE_ma
```
# 1.4 aggregate by item
## 1) Naive 
```{r warning=False}
cat_ts_list = lapply(trainAggCat[,2:ncol(trainAggCat)], ts)
cat_list_naive = lapply(cat_ts_list, naive, h=28)
cat_devisors = unlist(lapply(trainAggCat[,2:ncol(trainAggCat)], cal.devisor))
cat_RMSSE_v_naive = eval.RMSSE(testAggCat, cat_list_naive, h=28, devisor = cat_devisors)
cat_RMSSE_v_naive
```
## 2) sNaive 
```{r warning=False}
cat_ts_list = lapply(trainAggCat[,2:ncol(trainAggCat)], ts)
cat_list_snaive = lapply(cat_ts_list, snaive, h=28)
cat_devisors = unlist(lapply(trainAggCat[,2:ncol(trainAggCat)], cal.devisor))
cat_RMSSE_v_snaive = eval.RMSSE(testAggCat, cat_list_snaive, h=28, devisor = cat_devisors)
cat_RMSSE_v_snaive
```
## 4) MA 
```{r warning=False}
cat_ts_list = lapply(trainAggCat[,2:ncol(trainAggCat)], ts)
cat_list_ma = lapply(cat_ts_list, sma, h=28)
cat_devisors = unlist(lapply(trainAggCat[,2:ncol(trainAggCat)], cal.devisor))
cat_RMSSE_v_ma = eval.RMSSE(testAggCat, cat_list_ma, h=28, devisor = cat_devisors)
cat_RMSSE_v_ma
```


# 1.4 aggregate by store
## 1)Naive 
```{r warning=False}
store_ts_list = lapply(trainAggStore[,2:ncol(trainAggStore)], ts)
store_list_naive = lapply(store_ts_list, naive, h=28)
store_devisors = unlist(lapply(trainAggStore[,2:ncol(trainAggStore)], cal.devisor))
store_RMSSE_v_naive = eval.RMSSE(testAggStore, store_list_naive, h=28, devisor = store_devisors)
store_RMSSE_v_naive
```
## 2) sNaive 
```{r warning=False}
store_ts_list = lapply(trainAggStore[,2:ncol(trainAggStore)], ts)
store_list_snaive = lapply(store_ts_list, snaive, h=28)
store_devisors = unlist(lapply(trainAggStore[,2:ncol(trainAggStore)], cal.devisor))
store_RMSSE_v_snaive = eval.RMSSE(testAggStore, store_list_snaive, h=28, devisor = store_devisors)
store_RMSSE_v_snaive
```
## 4) MA 
```{r warning=False}
store_ts_list = lapply(trainAggStore[,2:ncol(trainAggStore)], ts)
store_list_ma = lapply(store_ts_list, sma, h=28)
store_devisors = unlist(lapply(trainAggStore[,2:ncol(trainAggStore)], cal.devisor))
store_RMSSE_v_ma = eval.RMSSE(testAggStore, store_list_ma, h=28, devisor = store_devisors)
store_RMSSE_v_ma
```

# 1.5 aggregate by week
## 1) Naive 
```{r warning=False}
week_ts_list = lapply(trainAggWeek[,2:ncol(trainAggWeek)], ts)
week_list_naive = lapply(week_ts_list, naive, h=4)
week_devisors = unlist(lapply(trainAggWeek[,2:ncol(trainAggWeek)], cal.devisor))
week_RMSSE_v_naive = eval.RMSSE(testAggWeek, week_list_naive, h = 4, devisor = week_devisors)
week_RMSSE_v_naive
```
## 2) sNaive 
```{r warning=False}
week_ts_list = lapply(trainAggWeek[,2:ncol(trainAggWeek)], ts)
week_list_snaive = lapply(week_ts_list, snaive, h=4)
week_devisors = unlist(lapply(trainAggWeek[,2:ncol(trainAggWeek)], cal.devisor))
week_RMSSE_v_snaive = eval.RMSSE(testAggWeek, week_list_snaive, h = 4, devisor = week_devisors)
week_RMSSE_v_snaive
```

## 4) MA 
```{r warning=False}
week_ts_list = lapply(trainAggWeek[,2:ncol(trainAggWeek)], ts)
week_list_ma = lapply(week_ts_list, sma, h=4)
week_devisors = unlist(lapply(trainAggWeek[,2:ncol(trainAggWeek)], cal.devisor))
week_RMSSE_v_ma = eval.RMSSE(testAggWeek, week_list_ma, h = 4, devisor = week_devisors)
week_RMSSE_v_ma
```