---
title: "Forecasting & Predictive Group Assignment"
author: "Kai KANG, Jiaqian MA, Yinzhe HUANG, Yue CHEN"
date: "2022/1/12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Assessing the data and univariate benchmarks

###1.1 Are these six variables stationary?

```{r include=FALSE}
# install.packages('tidyverse')
library(tidyverse)
rawData = read_csv("./dat/Projectdata.csv")
# spec(rawData)
```

### 1.2 Assess the set of benchmark in the M5 guidelines

#### ES, ESX, Holt-Winters

##### Source function
```{r}
source("./R/utils.R")
source("./R/dataUtils.R")
```

##### Dataset splition
```{r}
trainData = rawData[c(1:(nrow(rawData)-28)),]
testData = rawData[c((nrow(rawData)-27):nrow(rawData)),]
```

### Aggregation
```{r}
# by categories
trainAggCat = agg_by_cat(trainData)
testAggCat = agg_by_cat(testData)

# by store
trainAggStore = agg_by_store(trainData)
testAggStore = agg_by_store(testData)

# by week
trainAggWeek = agg_by_week(trainData)
testAggWeek = agg_by_week(testData)
```








##### ses
```{r warning=False} 
ts_list = lapply(trainData[,2:ncol(rawData)], ts)

devisors = unlist(lapply(trainData[,2:ncol(trainData)], cal.devisor))

ses_crossH_RMSSE = data.frame()
for (h in 1:28) {
  pred_list = lapply(ts_list, ses, h=h)
  ses_RMSSE_v = eval.RMSSE(testData, pred_list, h = h, devisor = devisors)
  ses_crossH_RMSSE = rbind(ses_crossH_RMSSE, ses_RMSSE_v)
}

names(ses_crossH_RMSSE) = names(ses_RMSSE_v)
print(ses_crossH_RMSSE)
```


# 1.4 aggregate by item
```{r warning=False}
cat_ts_list = lapply(trainAggCat[,2:ncol(trainAggCat)], ts)
cat_ses_list = lapply(cat_ts_list, ses, h=4)
cat_devisors = unlist(lapply(trainAggCat[,2:ncol(trainAggCat)], cal.devisor))
cat_ses_RMSSE_v = eval.RMSSE(testAggCat, cat_ses_list, h=4, devisor = cat_devisors)
print(cat_ses_RMSSE_v)
```
# 1.4 aggregate by store
```{r warning=False}
store_ts_list = lapply(trainAggStore[,2:ncol(trainAggStore)], ts)
store_ses_list = lapply(store_ts_list, ses, h=4)
store_devisors = unlist(lapply(trainAggStore[,2:ncol(trainAggStore)], cal.devisor))
store_ses_RMSSE_v = eval.RMSSE(testAggStore, store_ses_list, h=4, devisor = store_devisors)
print(store_ses_RMSSE_v)
```

# 1.5 aggregate by week
```{r warning=False}
week_ts_list = lapply(trainAggWeek[,2:ncol(trainAggWeek)], ts)
week_ses_list = lapply(week_ts_list, ses, h=4)
week_devisors = unlist(lapply(trainAggWeek[,2:ncol(trainAggWeek)], cal.devisor))
week_tbats_RMSSE_v = eval.RMSSE(testAggWeek, week_ses_list, h = 4, devisor = week_devisors)
print(week_tbats_RMSSE_v)
```











